# Login information (works with GMAIL after enabling insecure apps)
SENDER_EMAIL = ""
PASSWORD = ''


SENDER_NAME = ''

# SMTP Server Settings
SMTP_ADRESS = "smtp.gmail.com"
SSL_PORT = 465

#EMAIL RECEIVERS CSV FILE NAME (MUST CONTAIN A COLLOM NAMED "EMAIL")
CSV_FILE = ""

#TEXT FILE CONTAINING THE EMAIL BODY
TEXT_BODY_FILE = ""


# EMAIL SUBJECT
SUBJECT = ''

#Unsubscibing Section
EMAIL_FOLDER = "Inbox"

IMAP_ADRESS = 'imap.gmail.com'

CANCEL_SUBJECT_KEYWORD = ''

SEND_UNSUB_MESSAGE = True

UNSUB_MESSAGE_SUBJECT = ''

UNSUB_BODY_FILE = ''